title: Cat's Space
author: Cat
email: satisity@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a website created for an assignment on Roppers Academy.

# social links
twitter_username: hoppersroppers # DO NOT include the @ character, or else the build will fail!
github_username:  satisity # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
